// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC_kI4_TGXlM9uXh7tI95z9Vb1UULXWC0',
    appId: '1:433719632695:web:b2914b211ef716b5a6b0b2',
    messagingSenderId: '433719632695',
    projectId: 'kaig-28620',
    authDomain: 'kaig-28620.firebaseapp.com',
    storageBucket: 'kaig-28620.firebasestorage.app',
    measurementId: 'G-SF38YB9L2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSSb3XFAVPEWhiPOk1XHAzK04M6lELt5A',
    appId: '1:433719632695:android:20881b590c7e51b3a6b0b2',
    messagingSenderId: '433719632695',
    projectId: 'kaig-28620',
    storageBucket: 'kaig-28620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBouj2I4y4SzV9jdx8Tkhqmzj-3CqEgHok',
    appId: '1:433719632695:ios:faa051d7527aa634a6b0b2',
    messagingSenderId: '433719632695',
    projectId: 'kaig-28620',
    storageBucket: 'kaig-28620.firebasestorage.app',
    iosBundleId: 'com.CPD.kaig.kaig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBouj2I4y4SzV9jdx8Tkhqmzj-3CqEgHok',
    appId: '1:433719632695:ios:faa051d7527aa634a6b0b2',
    messagingSenderId: '433719632695',
    projectId: 'kaig-28620',
    storageBucket: 'kaig-28620.firebasestorage.app',
    iosBundleId: 'com.CPD.kaig.kaig',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC_kI4_TGXlM9uXh7tI95z9Vb1UULXWC0',
    appId: '1:433719632695:web:a199de801c534b10a6b0b2',
    messagingSenderId: '433719632695',
    projectId: 'kaig-28620',
    authDomain: 'kaig-28620.firebaseapp.com',
    storageBucket: 'kaig-28620.firebasestorage.app',
    measurementId: 'G-YV39B7CBJ3',
  );
}
