// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2oCJkPBKDQkNk0m-Kz7ipZSHJHZZh-Ds',
    appId: '1:448649256528:web:2ec75786d35fbb790f7b55',
    messagingSenderId: '448649256528',
    projectId: 'kaig-demo1',
    authDomain: 'kaig-demo1.firebaseapp.com',
    storageBucket: 'kaig-demo1.firebasestorage.app',
    measurementId: 'G-K37KTBSHRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNoF9ZNQMGLo8FeHf_UpnUGO3gxIE_l5g',
    appId: '1:448649256528:android:8c60c04faee715ec0f7b55',
    messagingSenderId: '448649256528',
    projectId: 'kaig-demo1',
    storageBucket: 'kaig-demo1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3tklNoDG4w3jEqDFG4QK-C282SVQ8-Bw',
    appId: '1:448649256528:ios:7d7a0382482c5e410f7b55',
    messagingSenderId: '448649256528',
    projectId: 'kaig-demo1',
    storageBucket: 'kaig-demo1.firebasestorage.app',
    iosBundleId: 'com.cpd.kaig.kaig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3tklNoDG4w3jEqDFG4QK-C282SVQ8-Bw',
    appId: '1:448649256528:ios:33f671e3e358cec60f7b55',
    messagingSenderId: '448649256528',
    projectId: 'kaig-demo1',
    storageBucket: 'kaig-demo1.firebasestorage.app',
    iosBundleId: 'com.CPD.kaig.kaig',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2oCJkPBKDQkNk0m-Kz7ipZSHJHZZh-Ds',
    appId: '1:448649256528:web:b22a7ba3bf6512920f7b55',
    messagingSenderId: '448649256528',
    projectId: 'kaig-demo1',
    authDomain: 'kaig-demo1.firebaseapp.com',
    storageBucket: 'kaig-demo1.firebasestorage.app',
    measurementId: 'G-2RNJ8KZSJB',
  );

}